# Generated by Django 5.1.7 on 2025-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('overload', 'Overload'), ('sensor_error', 'Sensor Error'), ('maintenance', 'Maintenance')], default='overload', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='alert_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_report_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_reported_location',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weight_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weightreading',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weightreading',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('suspected', 'Suspected')], default='valid', max_length=20),
        ),
    ]
