# Generated by Django 5.1.7 on 2025-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alert_location_alert_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightreading',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightreading',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
