# Generated by Django 5.1.7 on 2025-04-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_vehicle_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='is_resolved',
            new_name='notified',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_timestamp',
        ),
        migrations.AddField(
            model_name='alert',
            name='current_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('overload', 'Overload'), ('sensor_malfunction', 'Sensor Malfunction'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.vehicle'),
        ),
    ]
