# Generated by Django 5.1.7 on 2025-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
