# Generated by Django 5.1.7 on 2025-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_penaltyrate_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_currently_overloaded',
            field=models.BooleanField(default=False, help_text='Whether the vehicle is currently in an overloaded state'),
        ),
    ]
