# Generated by Django 5.1.7 on 2025-03-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alert_alert_type_alert_resolved_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='average_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightreading',
            name='sensor_health',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('malfunctioning', 'Malfunctioning')], default='healthy', max_length=50),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weight_summary', 'Weight Summary'), ('alert_summary', 'Alert Summary')], max_length=50)),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.vehicle')),
            ],
        ),
    ]
