# Generated by Django 5.1.7 on 2025-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
