# Generated by Django 5.1.7 on 2025-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_weightreading_latitude_weightreading_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
