# Generated by Django 5.1.7 on 2025-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_vehicle_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
