# Generated by Django 5.1.7 on 2025-04-08 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remove_alert_is_currently_overloaded_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'penalties'},
        ),
        migrations.AlterModelOptions(
            name='penaltyrate',
            options={'get_latest_by': 'effective_from'},
        ),
        migrations.AddField(
            model_name='penalty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where violation occurred', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where violation occurred', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this penalty'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='When the penalty was paid', null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Payment reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('waived', 'Waived')], default='unpaid', help_text='Current status of the penalty', max_length=10),
        ),
        migrations.AddField(
            model_name='penaltyrate',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this rate became effective'),
        ),
        migrations.AddField(
            model_name='penaltyrate',
            name='notes',
            field=models.TextField(blank=True, help_text='Reason for rate change'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Penalty amount in TZS', max_digits=12),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='overload_amount',
            field=models.DecimalField(decimal_places=2, help_text='How much the vehicle was overloaded (in kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether the penalty has been paid'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the penalty was issued'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle that received this penalty', on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='monitoring.vehicle'),
        ),
        migrations.AlterField(
            model_name='penaltyrate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Current penalty amount in TZS', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['vehicle', 'timestamp'], name='monitoring__vehicle_b3b503_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['status', 'paid'], name='monitoring__status_473306_idx'),
        ),
    ]
